storyblok.webhook:
    path: /webhook/{spaceId}/{urlSecret}
    controller: Torr\Storyblok\Webhook\Controller\WebhookController::webhook
    requirements:
        spaceId: \d+
        urlSecret: .*?
    defaults:
        urlSecret: ~

storyblok.asset-proxy:
    path: /asset/{spaceId}/{path}
    controller: Torr\Storyblok\Assets\Controller\AssetProxyController::proxyAsset
    requirements:
        spaceId: \d+
        path: .+?
