services:
    _defaults:
        autowire: true
        autoconfigure: true

    Torr\Storyblok\:
        resource: ../src/*
        exclude:
             - ../src/Api/Data
             - ../src/Exception
             - ../src/Field
             - ../src/Component/Filter
             - ../src/Manager/Sync/Filter
             - ../src/RichText
             - ../src/TorrStoryblokBundle.php

    Torr\Storyblok\Config\StoryblokConfig:
        $spaceId: !abstract set via config
        $managementToken: !abstract set via config
        $contentToken: !abstract set via config

    Torr\Storyblok\Cache\DebugCacheFactory:
        $isDebug: '%kernel.debug%'
