services:
    _defaults:
        autowire: true
        autoconfigure: true

    Torr\Storyblok\:
        resource: ../src/*
        exclude:
             - ../src/Api/Data
             - ../src/Exception
             - ../src/Field
             - ../src/TorrStoryblokBundle.php

    Torr\Storyblok\Config\StoryblokConfig:
        $spaceId: !abstract set via config
        $managementToken: !abstract set via config
        $contentToken: !abstract set via config


    Torr\Storyblok\Manager\ComponentManager:
        $components: !tagged_locator 'storyblok.component.definition'
