services:
    _defaults:
        autowire: true
        autoconfigure: true

    Torr\Storyblok\:
        resource: ../src/*
        exclude:
             - ../src/Data
             - ../src/Exception
             - ../src/Structure/Field/Option
             - ../src/TorrStoryblokBundle.php
