services:
    _defaults:
        autowire: true
        autoconfigure: true

    Torr\Storyblok\:
        resource: ../src/*
        exclude:
             - ../src/Api/Data
             - ../src/Exception
             - ../src/Field
             - ../src/Component/Filter
             - ../src/Manager/Sync/Filter
             - ../src/RichText/LinkMarksRichTextTransformer.php
             - ../src/RichText/RichTextTransformer.php
             - ../src/TorrStoryblokBundle.php

    Torr\Storyblok\Config\StoryblokConfig:
        $spaceId: !abstract set via config
        $managementToken: !abstract set via config
        $contentToken: !abstract set via config
