# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Torr\Storyblok\:
        resource: ../src/*
        exclude:
             - ../src/Api/Data
             - ../src/Api/Transformer/StoryblokIdSlugMapper.php
             - ../src/Api/ContentApi.php
             - ../src/Api/ManagementApi.php
             - ../src/Exception
             - ../src/Field
             - ../src/Component/Filter
             - ../src/Manager/Sync/Filter
             - ../src/RichText/LinkMarksRichTextTransformer.php
             - ../src/RichText/RichTextTransformer.php
             - ../src/TorrStoryblokBundle.php

    Torr\Storyblok\Config\StoryblokConfig:
        $spaceId: !abstract set via config
        $managementToken: !abstract set via config
        $contentToken: !abstract set via config
        $localeLevel: !abstract set via config
        $webhookSecret: !abstract set via config
        $allowUrlWebhookSecret: !abstract set via config

    Torr\Storyblok\Assets\Proxy\AssetProxy:
        $storagePath: '%kernel.project_dir%/var/storyblok/assets'
