services:
    _defaults:
        autowire: true
        autoconfigure: true

    Torr\Storyblok\:
        resource: ../src/*
        exclude:
             - ../src/Exception
             - ../src/Field
             - ../src/TorrStoryblokBundle.php
